name: release
on:
  push:
    branches: default

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout textadept-build dependencies
        uses: actions/checkout@v3
        with:
          repository: orbitalquark/textadept-build
          path: textadept-build
      - name: Build
        shell: bash
        run: |
          mkdir -p build/_deps && mv textadept-build/* build/_deps && rm -r textadept-build
          cmake -S . -B build -D CMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release --target diff -j
          cmake --install build --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            *.so
            *.dll
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Package
        shell: bash
        run: |
          git archive HEAD --prefix file_diff/ | tar -xf -
          mv *.so *.dll file_diff
          zip -r file_diff.zip file_diff
      - name: Tag
        run: |
          git tag latest
          git push -f origin latest
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: |
            Latest automated build (ignore github-actions' release date)

            Note: this build may only be compatible with the latest release of Textadept
            (which may be an unstable release or a nightly build). If you are looking for a
            version of this module that is compatible with a specific version of Textadept,
            please download the "modules.zip" archive released alongside your version of Textadept.
          artifacts: file_diff.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
