name: release
on:
  push:
    branch: default

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/orbitalquark/textadept-build:v1.0
    steps:
      - name: Checkout textadept
        uses: actions/checkout@v2
        with:
          repository: orbitalquark/textadept
          path: textadept
      - name: Checkout textadept-build dependencies
        uses: actions/checkout@v2
        with:
          repository: orbitalquark/textadept-build
          path: textadept-build
      - name: Checkout textadept-file-diff module
        uses: actions/checkout@v2
        with:
          path: textadept/modules/file_diff
      - name: Build
        shell: bash
        run: |
          mv textadept-build/* textadept/src && make -C textadept/src lua
          make -C textadept/modules/file_diff release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: textadept/modules/file_diff.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag
        run: |
          git tag latest
          git push -f origin latest
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: Latest automated build (ignore github-actions' release date)
          artifacts: textadept/modules/file_diff.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: [build, release]
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
